config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cnabs
  resources :transactions
  resources :stores
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "cnabs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cnab.rb
# frozen_string_literal: true

# An uploaded report that contains information about
# transactions to be created.
class Cnab < ApplicationRecord
  belongs_to :user
  has_many :transactions
  has_many :stores, through: :transactions
  has_one_attached :report

  validates :report, presence: true

  after_create :proccess_transactions

  # Returns an array of lines from the report file
  def report_lines
    LineBreaker.parse(download_report)
  end

  private

  # Proccesses transactions asynchronously
  def proccess_transactions
    CnabJob.perform_later(id: id)
  end

  # Download content from report file
  def download_report
    @report ||= ActiveStorage::Current.set(host: ENV['ACTIVESTORAGE_HOST']) do
      Net::HTTP.get URI.parse(report.service_url)
    end
  end
end

app/models/concerns/line_breaker.rb
# frozen_string_literal: false

module LineBreaker
  # Receives a file as argument and returns it's array of
  # lines, fixing encoding issues.
  def self.parse(file)
    file.force_encoding('UTF-8')
        .gsub("\xEF\xBB\xBF".force_encoding("UTF-8"), '')
        .split("\n")
  end
end

app/models/store.rb
# This class represent a store, a model that executes
# transactions to gain or spend it's balance.
class Store < ApplicationRecord
  has_many :transactions
end

app/models/transaction.rb
# frozen_string_literal: true

# This class represent each individual transaction that changes
# the total balance of a store.
class Transaction < ApplicationRecord
  belongs_to :store, counter_cache: true
  belongs_to :cnab, optional: true, counter_cache: true
  has_one :user, through: :cnab
  enum transaction_type: { debit: 1,
                           ticket: 2,
                           financing: 3,
                           credit: 4,
                           loan_receival: 5,
                           sales: 6,
                           ted_receival: 7,
                           doc_receival: 8,
                           rent: 9 }

  after_create :update_store_balance

  validate :double_charge

  # Returns a method to be used at the transaction on the store balance
  def signal
    sum? ? '+' : '-'
  end

  # Is this transaction a subtraction?
  def subtraction?
    %w[ticket financing rent].include? transaction_type
  end

  # Is this transaction a sum?
  def sum?
    !subtraction?
  end

  # Receives a line from a CNAB file and parses it into a Trasaction instance
  def self.create_from_cnab(line)
    raise Exception::ArgumentError("Invalid CNAB line for\n #{line}") unless line.size == 80
    create!(transaction_type: line[0].to_i,
            date: Date.parse(line[1..8]),
            value: line[9..18].to_f/100,
            cpf: line[19..29],
            card: line[30..41],
            time: line[42..47].gsub(/(\d{2})(?=\d)/, '\\1:'),
            store: Store.find_or_create_by(name: line[62..80], owner: line[48..61]))
  end

  private

  # Updates store balance based on value and transaction type
  def update_store_balance
    store.update(balance: store.balance.send("#{signal}", value))
  end

  # Validates value for double charging
  def double_charge
    errors.add(:value, "Double charging detected") if double_charge?
  end

  # Checks if transaction is a double charging by date, time, card and value
  def double_charge?
    Transaction.unscoped.where.not(id: id)
               .where(date: date,
                      time: time,
                      card: card,
                      value: value).exists?
  end
end

app/models/user.rb
# frozen_string_literal: true

# A user of the system, someone that can upload CNAB
# reports.
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable,
         omniauth_providers: %i[facebook]
  has_many :cnabs
  has_many :transactions, through: :cnabs
  has_many :stores, through: :cnabs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cnabs_controller.rb
# frozen_string_literal: true

class CnabsController < ApplicationController
  before_action :set_cnab, only: %i[show edit update destroy]

  # GET /cnabs
  # GET /cnabs.json
  def index
    @cnabs = current_user.cnabs.all.page params[:page]
  end

  # GET /cnabs/1
  # GET /cnabs/1.json
  def show
    @transactions = @cnab.transactions.page params[:page]
  end

  # GET /cnabs/new
  def new
    @cnab = current_user.cnabs.new
  end

  # POST /cnabs
  # POST /cnabs.json
  def create
    @cnab = current_user.cnabs.new(cnab_params)

    respond_to do |format|
      if @cnab.save
        format.html { redirect_to @cnab, notice: 'Cnab was successfully created.' }
        format.json { render :show, status: :created, location: @cnab }
      else
        format.html { render :new }
        format.json { render json: @cnab.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cnab
    @cnab = current_user.cnabs.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cnab_params
    params.require(:cnab).permit(:report)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = current_user.stores.includes(:transactions).page params[:page]
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @transactions = @store.transactions.page params[:page]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = current_user.stores.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cnabs_helper.rb
module CnabsHelper
end

app/views/cnabs/_form.html.erb
<%= form_with(model: cnab, local: true) do |form| %>
  <% if cnab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cnab.errors.count, "error") %> prohibited this cnab from being saved:</h2>

      <ul>
      <% cnab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :report %>
    <%= form.file_field :report %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cnabs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>CNABs</h1>
<%= link_to 'Submit a CNAB', new_cnab_path %>

<table>
  <thead>
    <tr>
      <%= page_entries_info @cnabs %>
    </tr>
    <tr>
      <th>Proccessed?</th>
      <th>Number of transactions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cnabs.each do |cnab| %>
      <tr>
        <td><%= cnab.proccessed_at.present? ? '✓' : 'X' %></td>
        <td><%= cnab.transactions_count %></td>
        <td><%= link_to 'Show', cnab %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <%= paginate @cnabs %>
  </tfoot>
</table>

app/views/cnabs/new.html.erb
<h1>New Cnab</h1>

<%= render 'form', cnab: @cnab %>

<%= link_to 'Back', cnabs_path %>

app/views/cnabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proccessed:</strong>
  <%= @cnab.proccessed_at.present? ? '✓' : 'X' %>
</p>

<% if @cnab.proccessed_at.present? %>
  <p>
    <strong>Proccessed at:</strong>
    <%= @cnab.proccessed_at %>
  </p>

  <table>
    <thead>
      <tr>
        <%= page_entries_info @transactions %>
      </tr>
      <tr>
        <th>Type</th>
        <th>Value</th>
        <th>Date</th>
        <th>Time</th>
        <th>CPF</th>
        <th>Card</th>
        <th>Store</th>
      </tr>
    </thead>

    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td>
            <%= transaction.transaction_type.titleize %>
          </td>
          <td>
            $<%= transaction.signal + ('%.2f' % transaction.value) %>
          </td>
          <td>
            <%= transaction.date %>
          </td>
          <td>
            <%= transaction.time.strftime("%H:%M:%S") %>
          </td>
          <td>
            <%= transaction.cpf %>
          </td>
          <td>
            <%= transaction.card %>
          </td>
          <td>
            <%= link_to transaction.store.name, transaction.store %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <%= paginate @transactions %>
    </tfoot>
  </table>
<% elsif @cnab.failure %>
  <p>
    <strong>Proccessing failed:</strong>
    <%= @cnab.failure_message %>
  </p>
<% else %>
  <p>
    <strong>Proccessing pending:</strong> ✓
  </p>
<% end %>

<%= link_to 'Back to CNABs', cnabs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BluTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav id="menu">
      <ul>
        <li>
          <%= link_to "CNAB Management", cnabs_url %>
        </li>
        <li>
          <%= link_to "Stores", stores_url %>
        </li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <%= page_entries_info @stores %>
    </tr>
    <tr>
      <th>Owner</th>
      <th>Name</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.owner %></td>
        <td><%= store.name %></td>
        <td>$ <%= '%.2f' % store.balance %></td>
        <td><%= link_to 'View Transactions', store %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <%= paginate @stores %>
  </tfoot>
</table>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @store.owner %>
</p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Balance:</strong>
  <%= '%.2f' % @store.balance %>
</p>

<p>
  <strong>Transactions:</strong>
</p>
<table>
  <thead>
    <tr>
      <%= page_entries_info @transactions %>
    </tr>
    <tr>
      <th>Type</th>
      <th>Value</th>
      <th>Date</th>
      <th>Time</th>
      <th>CPF</th>
      <th>Card</th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td>
          <%= transaction.transaction_type.titleize %>
        </td>
        <td>
          $<%= transaction.signal + ('%.2f' % transaction.value) %>
        </td>
        <td>
          <%= transaction.date %>
        </td>
        <td>
          <%= transaction.time.strftime("%H:%M:%S") %>
        </td>
        <td>
          <%= transaction.cpf %>
        </td>
        <td>
          <%= transaction.card %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <%= paginate @transactions %>
  </tfoot>
</table>

<%= link_to 'Back to Stores', stores_path %>